import Header from './components/Header';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='max-w-6xl mx-auto'>
				<Header />
				<div className='max-w-5xl mx-auto px-5'>{children}</div>
			</body>
		</html>
	);
}
